services:
  - type: web
    name: mebenmodel
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: build
        fromDatabase:
          name: mebenmodel-db
          property: connectionString
    healthCheckPath: /
    routes:
      - type: http
        path: /

  - type: pserv
    name: mebenmodel-db
    ipAllowList: []
    plan: free
    region: oregon
    database: mebenmodel
    user: mebenmodel
    postgresMajorVersion: 15
