services:
  - type: web
    name: mebenmodel
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --production=false --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
